# -*- coding: utf-8 -*-
"""One_Hot_Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cavChrhGZhPlY9SDCyQFC9j2ftn4NVJW

Determining the values of different car models with the help of linear regression whilst encoding the different car models.
"""

import pandas as pd
df = pd.read_csv("carprices.csv")
df

dummies = pd.get_dummies(df['Car Model'])
dummies

merged = pd.concat([df,dummies],axis='columns')
merged

final = merged.drop(["Car Model","Mercedez Benz C class"],axis='columns')
final

X = final.drop('Sell Price($)',axis='columns')
X

y = final['Sell Price($)']
y

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X,y)

model.score(X,y)

"""Price of mercedez benz that is 4 yr old with mileage 45000

"""

model.predict([[45000,4,0,0]])

"""Price of BMW X5 that is 7 yr old with mileage 86000"""

model.predict([[86000,7,0,1]])

